features:
  reviveBookEnabled: true
  heartUseEnabled: true
  withdrawCommandEnabled: true

gameplay:
  maxHealth: 40
  reviveHealth: 8
  dropHeartsIfMax: true

items:
  heartName: "<bold><#d9252e>Heart"
  heartLore: "<gray>Højreklik for at bruge!"
  reviveBookName: "<aqua>Revive Bog"
  reviveBookLore: "<dark_aqua>Rename denne bog med det spillernavn, du vil revive, og højreklik for at revive spilleren!"

recipes:
  customRecipesEnabled: true
  heartRecipeEnabled: true
  reviveBookRecipeEnabled: true

messages:
  prefix: "<dark_gray>[<red>Life<gold>Wars<dark_gray>]"
  announceAdminRevive: true
  usageError: "<red>Usage: %usage%"
  needToBePlayer: "<red>Du skal være en spiller for at bruge denne command"
  playerNotFound: "<red>Spiller ikke fundet!"
  disabledInConfigMsg: "<red>Denne funktion er disabled i config!"
  eliminateSuccess: "<gray>Du har elimineret <red>%player%<gray>!"
  reviveSuccess: "<gray>Du har revivet <red>%player%<gray>!"
  onlyReviveElimPlayers: "<red>Du kan kun revive elimineret spillere!"
  eliminatedJoin: "<red>Du har ikke flere hjerter!"
  eliminatedReason: "<dark_red>Ran out of lives."
  setHeartsConfirmSingle: "<gray>Satte <red>%player%<gray>'s hjerter til <red>%amount%<gray> hjerter"
  reloadMsg: "<gray>Genindlaeste pluginnet!"
  noWithdraw: "<red>Du bliver elimineret, hvis du withdrawer et heart!"
  withdrawMin: "<red>Du kan ikke withdraw mindre end 1 hjerte!"
  successWithdraw: "<gray>Du fik %amount%x <red>%item%<gray>!"
  maxHeartLimitReached: "<red>Du har allerede ramt %limit% hjerter!"
  recipeNotCraftable: "<red>Du kan ikke craft dette item!"
  recipeNotFound: "<red>Denne recipe eksistere ikke!"
  configKeyNotFound: "<red>Config key ikke fundet: %key%"
  configUpdated: "<gray>Config value <red>%key%<gray> sat til <red>%value%"
